### ISSUE TITLE
Should stop station on exit

### ISSUE THREAD

**Issue by thierry7100** [Tom-Hirschberger/MMM-MplayerRadio#18]
Hi, 

First, thanks for this module !
I found a slight issue, when magic mirror exit, mplayer doesn't stop.
A stop function in the node_helper.js like this one corrects this problem.

  stop: function () {
    const self = this
    self.stopStation(false)
  },

**Comment by Tom-Hirschberger** [comment]
Hi,

as mplayer had been run as an sub-process of electron it had been stopped with the electron process in previous versions maybe this behavior changed in recent versions. 
I will check your solution and release a new version if it works.

**Comment by Tom-Hirschberger** [comment]
Thank you. Your fix worked great. Version 0.0.9 contains the fix now
