### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by MarcoNoah** [Tom-Hirschberger/MMM-MplayerRadio#3]
I love your module.

I am having a problem is finding the M3U file for radio stations.  Coudl you show me how.  For example I would like to put on teh module an English radio station Magic 105.4.  I have followed your instructions but an M3U file downloads but I do not know how to find the relevant code to add to the config file.

Many thanks

Steven

**Comment by Tom-Hirschberger** [comment]
Hi,
great that you like the module.
Do you mean Magic 105.4 played broadcased of London? Searched at my favorite website providing m3us (www.surfmusic.de) and found this on: http://www.surfmusic.de/radio-station/magic-105-4-fm,10170.html

There is a link on the page which should be used for "Standalone Players" which provides the link needed by the module (http://www.surfmusic.de/m3u/magic-105-4-fm,10170.m3u).

If you like to add an logo you can use this url: https://media.info/i/lv/magic-radio/1504126775/197.png

**Comment by Tom-Hirschberger** [comment]
Maybe the Readme is misleading. You do not need to download the m3u file. Simply do a right click and copy the url of it. This is the url you need for configuration.

**Comment by MarcoNoah** [comment]
Thank you.

 

I realised earlier today.  I was able to get some other uk Stations to play.

 

Magic using the M3U code doesn’t’ play.  Also when the other stations play the module flashes.  Is there anything I can do to stop this?

 

Steven

**Comment by Tom-Hirschberger** [comment]
Hi,
just had a couple of minutes and tried the m3u of Magic 105.4 in my setup. You are right. There seems to be a problem with the station stream and mplayer. Also tried to improve the playback by adjusting the cache but nothing seems to work.

But i found an other way to update the information of the currently playing stream which should reduce the flickering massively. Currently the new code is still in my dev branch. Maybe you want to give it a try. Simply change to the module directory and run the following code:
git checkout development
git pull
rm -rf node_modules package-lock.json
npm install

Ps.: If you want to change back to the branch containing my stable code, you only need to do the following steps:
git checkout master
git pull
rm -rf node_modules package-lock.json
npm install

**Comment by MarcoNoah** [comment]
Dear Thomas

 

Thank you again for taking the time to respond which is much appreciated.

 

I found by accident that the station loads after about 3-4 minutes .

 

I will try your update.

 

Kind regards

Steven

**Comment by Tom-Hirschberger** [comment]
Hi, i checked in a new version a view minutes ago. The "flickering fix" caused the module to display the wrong state after the station got toggled. Now everything works as expected.

**Comment by Tom-Hirschberger** [comment]
Hi,
i think i found an solution for the Magic 105.4 problem.
I already developed a script to use xmm2 instead of mplayer to play the stations. It is possible to use mplayer for all "normal" stations and the script to play Magic 105.4 with xmms2.
You need to have xmms2 installed on the pi (if not run "sudo apt update && sudo apt install xmms2").
If you add the following to your config:

{
						title: "Magic",
						url: "https://stream-mz.planetradio.co.uk/magic1054.aac?direct=true",
						logo: "https://media.info/i/lv/magic-radio/1504126775/197.png",
						customCommand: "/home/pi/MagicMirror/modules/MMM-MplayerRadio/scripts/playRadio.bash",
						customCommandArgs: ["###URL###"],
},

Magic will be played with xmms2.

The only disadvantage of xmms2 is that there will be no information about the currently streamed content.

**Comment by MarcoNoah** [comment]
Dear Thomas

 

You are very kind to keep on this issue.

 

I will certainly give this a try.  Magic does work after a few minutes  but let see what happens.

 

Kind regards


Steven

**Comment by Tom-Hirschberger** [comment]
Hi,
i tested the new "features" the last days and everything seems to work fine. I also used the Magic station for a couple of days and the workaround with xmms2 reduces the loading time as expected. I think i will merge the changes to the master branch these days. If it is ok for you i will close the ticket, now?

**Comment by MarcoNoah** [comment]
Thank you Thomas you are very kind.

**Comment by Tom-Hirschberger** [comment]
Hi,
i merged the code a few minutes ago and will close the ticket now. I wish you a lot of fun with the module.

**Comment by MarcoNoah** [comment]
Dear Thomas

 

I hope you do not mind me contacting you again.  The module is working really well.

 

How can I get the volume buttons to work?  I am not quite sure what I need to add to the config file.

 

I hope you are keeping safe!

 

Kind regards

Steven

**Comment by Tom-Hirschberger** [comment]
Hi,

no problem you are welcome.
I added an hint to the readme recently because an other user had the same problem.
The buttons only itiate an notification to an other module. You need to install [MMM-Volume](https://github.com/Anonym-tsk/MMM-Volume) to get the buttons work.

**Comment by MarcoNoah** [comment]
Thank you .

 

Keep safe!
