### ISSUE TITLE
server mode

### ISSUE THREAD

**Issue by AGUERY** [Tom-Hirschberger/MMM-MplayerRadio#6]
Hello 

Does it work in server only mode ?

Thanks 

Aurelien

**Comment by Tom-Hirschberger** [comment]
Hi,the module works without being displayed so I do not think there will be any problem during server only mode. It still can be controlled with notifications or you can use the autoplay feature.Your welcomeThomasAm 08.12.2020 22:10 schrieb AGUERY <notifications@github.com>:
Hello
Does it work in server only mode ?
Thanks
Aurelien

**Comment by Tom-Hirschberger** [comment]
Hi,

sorry, I think I miss understood your question.
The music will be played on the pi. There is no possibility to play it on the client if this is your question.
